services:

    seipp.vipp.initialize:
        class: PRESTEP\BookingPlanBundle\EventListener\System
        tags:
            - { name: contao.hook, hook: initializeSystem, method: initializeSystem, priority: -256 }
        arguments:
            - "@request_stack"
            - "@contao.routing.scope_matcher"