services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    prestep_bookingplan.navigation_listener:
        class: PRESTEP\BookingPlanBundle\EventListener\NavigationListener
        arguments:
            - "@request_stack"
            - "@router"
        tags:
            - { name: contao.hook, hook: getUserNavigation }

    prestep.bookingplan.room.dca.tl_prestep_bookingplan_room:
        class: PRESTEP\BookingPlanBundle\Dca\Room
        public: true
        arguments:
            - "@contao.framework"
            - "@security.token_storage"
            - "@session"
            - "doctrine.orm.entity_manager"